version: '3.5'

services:
  backend:
    build: ../../backend
    ports:
      - 8000:8000
    volumes:
      - ../../backend:/mydir
  frontend:
    build: ../../frontend
    ports:
      - 5000:5000
    volumes:
      - ../../frontend:/mydir