version: '3.5'

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
    ports:
      - 5432:5432
  backend:
    build: ../../backend
    ports:
      - 8000:8000
    volumes:
      - ../../backend:/mydir
    links:
      - db
    environment:
      - FRONT_URL=http://localhost:5000 
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_HOST=db
  frontend:
    build: ../../frontend
    ports:
      - 5000:5000
    volumes:
      - ../../frontend:/mydir
    environment:
      - API_URL=http://localhost:8000
