version: '3.5'

services:
  redis:
    image: redis:alpine
    volumes:
      - .:/data
    restart: unless-stopped
    ports:
      - 6379:6379
  backend:
    build: ../../backend
    ports:
      - 8000:8000
    volumes:
      - ../../backend:/mydir
    links:
      - redis
  frontend:
    build: ../../frontend
    ports:
      - 5000:5000
    volumes:
      - ../../frontend:/mydir
