version: '3.5'

services:
  training:
    build: ./training
    volumes:
      - ./training/data:/src/data
      - ./training/imgs:/src/imgs
      - ./training/model:/model
  # backend:
  #   build: ./backend
  #   ports:
  #     - 5000:5000
  #   environment:
  #     - FRONT_URL=http://localhost:3000
  #   volumes:
  #     - model:/src/model
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - API_URL=http://localhost:5000

volumes:
  model: